---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password-sdk
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: jyasslze4xyjutcdnn74dbaicq
      auth:
        serviceAccountSecretRef:
          name: 1password-token-shadesmar
          key: token